### ISSUE TITLE
Web Socket can't open with SSL

### ISSUE THREAD

**Issue by mangalauoc** [farsunset/cim#15]
How to configure the SSL for web socket? I configured SSL to the Application but socket still comming as ws:// not wss://

**Comment by farsunset** [comment]
To open ssl configured on nginx layer is most suitable.  not at  configured application.

**Comment by mangalauoc** [comment]
Currently, I run this application inside the tomcat server. Automatically WebSocket port(34567) and AppSockets port (23456) are initializing without SSL. I mean ws://. I only have added small configurations to set the SSL to the Application like follows. Are those configurations Correct or wrong?

**server.ssl.key-store=classpath:cert.p12**
**server.ssl.key-store-password=my password**
**server.ssl.keyStoreType=PKCS12**

but I don't know how to config the SSL inside the Nginx. Can I get an example or help? Please

**Comment by farsunset** [comment]
> Currently, I run this application inside the tomcat server. Automatically WebSocket port(34567) and AppSockets port (23456) are initializing without SSL. I mean ws://. I only have added small configurations to set the SSL to the Application like follows. Are those configurations Correct or wrong?
> 
> **server.ssl.key-store=classpath:cert.p12**
> **server.ssl.key-store-password=my password**
> **server.ssl.keyStoreType=PKCS12**
> 
> but I don't know how to config the SSL inside the Nginx. Can I get an example or help? Please

https://www.serverlab.ca/tutorials/linux/web-servers-linux/how-to-proxy-wss-websockets-with-nginx/

**Comment by farsunset** [comment]
Or  you can modify cim-server-sdk-netty to add ssl feature 
https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/websocketx/server/WebSocketServer.java
