### ISSUE TITLE
在bugly中收集到了8.0以上的系统在后台时启动service会报错，经查阅8.0好像需要startForegroundService方式启动

### ISSUE THREAD

**Issue by JayPhone** [farsunset/cim#4]
![48458043-A9A0-4d4a-88B3-1C65EB9A2ACE](https://user-images.githubusercontent.com/18634001/56184999-b44a6200-604e-11e9-9201-fd1af41ad2d6.png)
![TIM截图20190416135146](https://user-images.githubusercontent.com/18634001/56185033-d0e69a00-604e-11e9-892e-dc456cbbe1e5.png)
麻烦大佬看看是不是存在相关问题

**Comment by farsunset** [comment]
targetversion改为小于26即可，这个是8.0的限制 还没找到更好的解决方案

**Comment by farsunset** [comment]
已经解决了 更新一下

**Comment by JayPhone** [comment]
好的，谢谢大佬，我试试

**Comment by JayPhone** [comment]
大佬，好像引入新的bug
![TIM截图20190417180800](https://user-images.githubusercontent.com/18634001/56280151-32d0fd80-613c-11e9-9cc1-2d27b59895e2.png)
测试手机 小米3，系统版本6.0

**Comment by farsunset** [comment]
mainfest文件里面  修改一下provider的地址

**Comment by farsunset** [comment]
```
<provider
            android:name="com.farsunset.cim.sdk.android.CIMCacheProvider"
            android:authorities="com.farsunset.ichat.example.cim.provider"
            android:process=":cimpush"
            android:exported="false" />
        <!-- android:authorities="${package}.cim.provider"-->
```
修改一下android:authorities地址

**Comment by JayPhone** [comment]
解决了，感谢感谢

**Comment by JayPhone** [comment]
![TIM截图20190418141423](https://user-images.githubusercontent.com/18634001/56340611-fdccb580-61e4-11e9-9348-e0d2b5e8e652.png)
![TIM截图20190418141805](https://user-images.githubusercontent.com/18634001/56340618-00c7a600-61e5-11e9-9e46-25b826db2c15.png)
发现新的异常，在API27的模拟器上会报以上异常

**Comment by farsunset** [comment]
更新再试一下吧
