### ISSUE TITLE
集群获取session

### ISSUE THREAD

**Issue by zachxiaoyu** [farsunset/cim#6]
集群获取session时这句话“session.setIoSession(nioSocketAcceptor.getManagedSessions().get(session.getNid()));”中无法为获取到的session设置属性setIoSession.请问是什么原因呢？

**Comment by farsunset** [comment]
只能获取连接到当前服务器的session，集群环境下，可以做一个发送消息的网关接口，通过接受者账号连接到哪台服务器，然后转发给目标服务器来做消息发送
